"""Typed data structures exchanged by scanner modules and report writers."""

from __future__ import annotations

from dataclasses import asdict, dataclass, field
from datetime import UTC, datetime
from enum import StrEnum
from typing import Any


class Severity(StrEnum):
    """Severity levels used for observations, not exploitability claims."""

    INFO = "info"
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"


@dataclass(slots=True)
class Finding:
    """A non-destructive observation generated by an assessment module."""

    title: str
    severity: Severity
    description: str
    evidence: str
    recommendation: str
    module: str
    cvss: str = ""
    url: str = ""


@dataclass(slots=True)
class ModuleResult:
    """Structured output from a single scanner module."""

    module: str
    data: dict[str, Any] = field(default_factory=dict)
    findings: list[Finding] = field(default_factory=list)
    errors: list[str] = field(default_factory=list)
    duration_ms: int = 0


@dataclass(slots=True)
class ScanReport:
    """Complete scan output that can be rendered in several formats."""

    target: str
    started_at: str
    finished_at: str
    authorized: bool
    version: str
    modules: list[ModuleResult]
    statistics: dict[str, int]
    notice: str = (
        "Sentinel performs only non-destructive checks. Results are observations, "
        "not proof of a vulnerability. Verify scope and findings manually."
    )

    @classmethod
    def create(cls, target: str, authorized: bool, version: str) -> ScanReport:
        """Create an empty report with a UTC start time."""
        now = datetime.now(UTC).isoformat()
        return cls(
            target=target,
            started_at=now,
            finished_at=now,
            authorized=authorized,
            version=version,
            modules=[],
            statistics={},
        )

    def as_dict(self) -> dict[str, Any]:
        """Return a serialization-friendly representation."""
        return asdict(self)
